### PR TITLE
firmware: remove all firmware files available in kernel repo

### PR DESCRIPTION
**Pull request by MilhouseVH**
This removes all firmware files that are available in the kernel repository (formerly x86-firmware) repo [here](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/).

The only files that need to be in this repo are those firmware files that don't exist anywhere else, or at least not in the kernel repo.

At this time, this is:
```
7ba1f3084a61a4bcf7b8c8396e8a4201  ./brcm/BCM20702A0-0a5c-21e8.hcd
7ba1f3084a61a4bcf7b8c8396e8a4201  ./brcm/fw-0a5c_21e8.hcd
7ba1f3084a61a4bcf7b8c8396e8a4201  ./fw-0a5c_21e8.hcd
99d4b41a23d6551090955cc42f92d3f4  ./brcm/BCM20702A0-0a5c-21ec.hcd
99d4b41a23d6551090955cc42f92d3f4  ./brcm/fw-0a5c_21ec.hcd
99d4b41a23d6551090955cc42f92d3f4  ./fw-0a5c_21ec.hcd
b95ee9032a723daa25ab9608a515e984  ./brcm/BCM43430A1.hcd
```

The first 6 files all appear to be variations of each other - I'd expect we can remove some of these (ie. 4 of them). Any suggestions?

The last file, `brcm/BCM43430A1.hcd`, is the RPi3 bluetooth firmware - I'm not sure if we need this here, as it's also installed by [brcmfmac_sdio-firmware-rpi](https://github.com/LibreELEC/LibreELEC.tv/tree/master/packages/linux-firmware/brcmfmac_sdio-firmware-rpi).

### CODE REVIEW

**Comment by chewitt** [comment]
firmware/intel has symlinks for files which have alternate names so you could do the same for the brcm folder. It won't save space in images (as squashfs de-dupes) but it's cleaner. I'd drop the Pi3 firmware if it's available from the other package.

**Comment by MilhouseVH** [comment]
Dropped the RPi0/RPi3 firmware, switched to sym links

**Comment by MilhouseVH** [comment]
Added 91606f0d28530adeade7a94525210968bd7edec4, see #2

**Comment by chewitt** [comment]
@MilhouseVH thanks for this.. let's see what breaks :)

**Pull request merged**
